[package]
name = "muxe-adapter-herdr"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
muxe-adapter-api = { path = "../muxe-adapter-api" }
muxe-core = { path = "../muxe-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
nix.workspace = true
regex.workspace = true
regress.workspace = true
thiserror.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
muxe-adapter-zellij = { path = "../muxe-adapter-zellij" }
muxe-protocol = { path = "../muxe-protocol" }
muxe-zellij-protocol = { path = "../muxe-zellij-protocol" }
