use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use eyre::{Result, WrapErr, bail};
use schemars::schema::RootSchema;
use serde_json::Value;
use sha2::{Digest, Sha256};
use typify::{TypeSpace, TypeSpaceSettings};

const DEFAULT_INPUT: &str = "fixtures/herdr/herdr-api.schema.json";
const DEFAULT_OUTPUT: &str = "crates/muxe-adapter-herdr/src/generated.rs";

#[derive(Debug, Clone, PartialEq, Eq)]
struct Method {
    name: String,
    native_type: String,
    params_ref: String,
    params_type: String,
    streaming: bool,
}

#[derive(Debug)]
struct Arguments {
    input: PathBuf,
    output: PathBuf,
    check: bool,
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error:?}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<()> {
    let arguments = parse_arguments(env::args().skip(1))?;
    let source = fs::read_to_string(&arguments.input)
        .wrap_err_with(|| format!("could not read {}", arguments.input.display()))?;
    let schema: Value = serde_json::from_str(&source)
        .wrap_err_with(|| format!("could not parse {}", arguments.input.display()))?;
    let output = generate(&schema)?;

    if arguments.check {
        let existing = fs::read_to_string(&arguments.output)
            .wrap_err_with(|| format!("could not read {}", arguments.output.display()))?;
        if existing != output {
            bail!(
                "{} is not reproducible from {}; run muxe-herdr-gen",
                arguments.output.display(),
                arguments.input.display()
            );
        }
        return Ok(());
    }

    if let Some(parent) = arguments.output.parent() {
        fs::create_dir_all(parent)
            .wrap_err_with(|| format!("could not create {}", parent.display()))?;
    }
    fs::write(&arguments.output, output)
        .wrap_err_with(|| format!("could not write {}", arguments.output.display()))?;
    Ok(())
}

fn parse_arguments(arguments: impl IntoIterator<Item = String>) -> Result<Arguments> {
    let mut input = PathBuf::from(DEFAULT_INPUT);
    let mut output = PathBuf::from(DEFAULT_OUTPUT);
    let mut check = false;
    let mut arguments = arguments.into_iter();

    while let Some(argument) = arguments.next() {
        match argument.as_str() {
            "--input" => input = PathBuf::from(next_value(&mut arguments, "--input")?),
            "--output" => output = PathBuf::from(next_value(&mut arguments, "--output")?),
            "--check" => check = true,
            "--help" | "-h" => {
                println!("Usage: muxe-herdr-gen [--input PATH] [--output PATH] [--check]");
                std::process::exit(0);
            }
            _ => bail!("unknown argument {argument:?}"),
        }
    }

    Ok(Arguments {
        input,
        output,
        check,
    })
}

fn next_value(arguments: &mut impl Iterator<Item = String>, option: &str) -> Result<String> {
    arguments
        .next()
        .ok_or_else(|| eyre::eyre!("{option} requires a path"))
}

fn generate(schema: &Value) -> Result<String> {
    let protocol = schema
        .get("protocol")
        .and_then(Value::as_u64)
        .ok_or_else(|| eyre::eyre!("top-level protocol must be an unsigned integer"))?;
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or_else(|| eyre::eyre!("top-level schema_version must be an unsigned integer"))?;
    let request = schema
        .pointer("/schemas/request")
        .cloned()
        .ok_or_else(|| eyre::eyre!("schema has no schemas.request"))?;
    let methods = methods(&request)?;
    let type_tokens = generate_request_types(request)?;
    let source_hash = sha256_hex(&canonical_json(schema)?);

    let mut generated = String::from(
        "// @generated by tools/muxe-herdr-gen; do not edit by hand.\n\
         // Regenerate with: cargo run -p muxe-herdr-gen -- --check\n\n",
    );
    writeln!(generated, "pub const BUNDLED_PROTOCOL: u64 = {protocol};")?;
    writeln!(generated, "pub const BUNDLED_SCHEMA_VERSION: u64 = {schema_version};")?;
    writeln!(
        generated,
        "pub const BUNDLED_SCHEMA_SHA256: &str = \"{source_hash}\";\n"
    )?;
    generated.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct MethodMetadata {\n\
         \tpub method: &'static str,\n\
         \tpub native_type: &'static str,\n\
         \tpub params_ref: &'static str,\n\
         \tpub params_type: &'static str,\n\
         \tpub streaming: bool,\n\
         }\n\n\
         pub const METHODS: &[MethodMetadata] = &[\n",
    );
    for method in &methods {
        writeln!(
            generated,
            "    MethodMetadata {{ method: {:?}, native_type: {:?}, params_ref: {:?}, params_type: {:?}, streaming: {} }},",
            method.name,
            method.native_type,
            method.params_ref,
            method.params_type,
            method.streaming,
        )?;
    }
    generated.push_str(
        "];\n\n\
         pub fn method_metadata(method: &str) -> Option<&'static MethodMetadata> {\n\
         \tMETHODS.iter().find(|metadata| metadata.method == method)\n\
         }\n\n\
         pub fn metadata_for_native_type(native_type: &str) -> Option<&'static MethodMetadata> {\n\
         \tMETHODS.iter().find(|metadata| metadata.native_type == native_type)\n\
         }\n\n\
         #[allow(clippy::all, dead_code)]\n\
         pub mod request_types {\n",
    );
    for line in type_tokens.lines() {
        writeln!(generated, "    {line}")?;
    }
    generated.push_str("}\n");
    Ok(generated)
}

fn methods(request: &Value) -> Result<Vec<Method>> {
    let branches = request
        .get("oneOf")
        .and_then(Value::as_array)
        .ok_or_else(|| eyre::eyre!("schemas.request.oneOf must be an array"))?;
    let mut methods = Vec::with_capacity(branches.len());

    for branch in branches {
        let properties = branch
            .get("properties")
            .and_then(Value::as_object)
            .ok_or_else(|| eyre::eyre!("request branch has no properties"))?;
        let name = properties
            .get("method")
            .and_then(|method| method.get("const"))
            .and_then(Value::as_str)
            .ok_or_else(|| eyre::eyre!("request branch method must have a string const"))?;
        let params_ref = properties
            .get("params")
            .and_then(|params| params.get("$ref"))
            .and_then(Value::as_str)
            .ok_or_else(|| eyre::eyre!("request method {name:?} params must be a $ref"))?;
        let params_type = params_ref
            .rsplit('/')
            .next()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| eyre::eyre!("request method {name:?} has invalid params ref"))?;
        methods.push(Method {
            name: name.to_owned(),
            native_type: method_to_native_type(name)?,
            params_ref: params_ref.to_owned(),
            params_type: params_type.to_owned(),
            streaming: name == "events.subscribe",
        });
    }

    methods.sort_by(|left, right| left.name.cmp(&right.name));
    if methods.windows(2).any(|pair| pair[0].name == pair[1].name) {
        bail!("request schema contains a duplicate method name");
    }
    Ok(methods)
}

fn method_to_native_type(method: &str) -> Result<String> {
    let (namespace, verb) = method
        .rsplit_once('.')
        .ok_or_else(|| eyre::eyre!("Herdr method {method:?} has no namespace separator"))?;
    if namespace.is_empty() || verb.is_empty() {
        bail!("Herdr method {method:?} has an empty namespace or verb");
    }
    Ok(format!(
        "native.herdr.{namespace}:{}",
        verb.replace('_', "-")
    ))
}

fn generate_request_types(mut request: Value) -> Result<String> {
    rewrite_request_references(&mut request);
    let root: RootSchema = serde_json::from_value(request)
        .wrap_err("could not convert Herdr request schema to schemars RootSchema")?;
    let mut types = TypeSpace::new(&TypeSpaceSettings::default());
    types
        .add_root_schema(root)
        .wrap_err("typify could not generate Herdr request types")?;
    let syntax = syn::parse_file(&types.to_stream().to_string())
        .wrap_err("typify emitted invalid Rust for the Herdr request schema")?;
    Ok(prettyplease::unparse(&syntax))
}

fn rewrite_request_references(schema: &mut Value) {
    match schema {
        Value::Object(object) => {
            if let Some(definitions) = object.remove("$defs") {
                object.insert("definitions".to_owned(), definitions);
            }
            for value in object.values_mut() {
                rewrite_request_references(value);
            }
        }
        Value::Array(values) => {
            for value in values {
                rewrite_request_references(value);
            }
        }
        Value::String(value) => {
            if let Some(rewritten) = value.strip_prefix("#/schemas/request/$defs/") {
                *value = format!("#/definitions/{rewritten}");
            }
        }
        _ => {}
    }
}

fn canonical_json(value: &Value) -> Result<Vec<u8>> {
    let mut canonical = value.clone();
    sort_json(&mut canonical);
    serde_json::to_vec(&canonical).wrap_err("could not serialize canonical schema")
}

fn sort_json(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let mut entries = std::mem::take(object).into_iter().collect::<Vec<_>>();
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            for (_, value) in &mut entries {
                sort_json(value);
            }
            object.extend(entries);
        }
        Value::Array(values) => {
            for value in values {
                sort_json(value);
            }
        }
        _ => {}
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("{digest:x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn native_method_names_round_trip_through_metadata() {
        assert_eq!(
            method_to_native_type("plugin.action.invoke").unwrap(),
            "native.herdr.plugin.action:invoke"
        );
        assert_eq!(
            method_to_native_type("server.reload_config").unwrap(),
            "native.herdr.server:reload-config"
        );
    }

    #[test]
    fn canonicalization_sorts_nested_object_keys() {
        let input = serde_json::json!({"b": {"z": 1, "a": 2}, "a": true});
        assert_eq!(
            String::from_utf8(canonical_json(&input).unwrap()).unwrap(),
            r#"{"a":true,"b":{"a":2,"z":1}}"#,
        );
    }

    #[test]
    fn rewrites_only_request_local_references() {
        let mut schema = serde_json::json!({
            "$defs": {"Thing": {"type": "string"}},
            "$ref": "#/schemas/request/$defs/Thing",
            "description": "#/schemas/success_response/$defs/Thing",
        });
        rewrite_request_references(&mut schema);
        assert_eq!(schema["$ref"], "#/definitions/Thing");
        assert_eq!(
            schema["description"],
            "#/schemas/success_response/$defs/Thing"
        );
        assert!(schema.get("$defs").is_none());
        assert!(schema.get("definitions").is_some());
    }
}
