mod classification;

use std::{collections::BTreeMap, env, fmt::Write as _, fs, path::PathBuf, process::ExitCode};

use eyre::{Result, WrapErr, bail};
use schemars::schema::RootSchema;
use serde_json::Value;
use sha2::{Digest, Sha256};
use typify::{TypeSpace, TypeSpaceSettings};

use crate::classification::Transport;

const DEFAULT_INPUT: &str = "fixtures/herdr/herdr-api.schema.json";
const DEFAULT_OUTPUT: &str = "crates/muxe-adapter-herdr/src/generated.rs";

#[derive(Debug, Clone, PartialEq, Eq)]
struct Method {
    name: String,
    native_type: String,
    params_ref: String,
    params_type: String,
    transport: Transport,
}

#[derive(Debug)]
struct Arguments {
    input: PathBuf,
    output: PathBuf,
    check: bool,
}

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error:?}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<()> {
    let arguments = parse_arguments(env::args().skip(1))?;
    let source = fs::read_to_string(&arguments.input)
        .wrap_err_with(|| format!("could not read {}", arguments.input.display()))?;
    let schema: Value = serde_json::from_str(&source)
        .wrap_err_with(|| format!("could not parse {}", arguments.input.display()))?;
    let raw_provenance_sha256 = sha256_hex(source.as_bytes());
    let output = generate(&schema, &raw_provenance_sha256)?;

    if arguments.check {
        let existing = fs::read_to_string(&arguments.output)
            .wrap_err_with(|| format!("could not read {}", arguments.output.display()))?;
        if existing != output {
            bail!(
                "{} is not reproducible from {}; run muxe-herdr-gen",
                arguments.output.display(),
                arguments.input.display()
            );
        }
        return Ok(());
    }

    if let Some(parent) = arguments.output.parent() {
        fs::create_dir_all(parent)
            .wrap_err_with(|| format!("could not create {}", parent.display()))?;
    }
    fs::write(&arguments.output, output)
        .wrap_err_with(|| format!("could not write {}", arguments.output.display()))?;
    Ok(())
}

fn parse_arguments(arguments: impl IntoIterator<Item = String>) -> Result<Arguments> {
    let mut input = PathBuf::from(DEFAULT_INPUT);
    let mut output = PathBuf::from(DEFAULT_OUTPUT);
    let mut check = false;
    let mut arguments = arguments.into_iter();

    while let Some(argument) = arguments.next() {
        match argument.as_str() {
            "--input" => input = PathBuf::from(next_value(&mut arguments, "--input")?),
            "--output" => output = PathBuf::from(next_value(&mut arguments, "--output")?),
            "--check" => check = true,
            "--help" | "-h" => {
                println!("Usage: muxe-herdr-gen [--input PATH] [--output PATH] [--check]");
                std::process::exit(0);
            }
            _ => bail!("unknown argument {argument:?}"),
        }
    }

    Ok(Arguments {
        input,
        output,
        check,
    })
}

fn next_value(arguments: &mut impl Iterator<Item = String>, option: &str) -> Result<String> {
    arguments
        .next()
        .ok_or_else(|| eyre::eyre!("{option} requires a path"))
}

fn generate(schema: &Value, raw_provenance_sha256: &str) -> Result<String> {
    let protocol = schema
        .get("protocol")
        .and_then(Value::as_u64)
        .ok_or_else(|| eyre::eyre!("top-level protocol must be an unsigned integer"))?;
    let schema_version = schema
        .get("schema_version")
        .and_then(Value::as_u64)
        .ok_or_else(|| eyre::eyre!("top-level schema_version must be an unsigned integer"))?;
    let request = schema
        .pointer("/schemas/request")
        .cloned()
        .ok_or_else(|| eyre::eyre!("schema has no schemas.request"))?;
    let methods = methods(&request)?;
    let request_schema_sha256 = sha256_hex(&canonical_json(&request)?);
    let type_tokens = generate_request_types(request)?;

    let mut generated = String::from(
        "// @generated by tools/muxe-herdr-gen; do not edit by hand.\n\
         // Regenerate with: cargo run --locked -p muxe-herdr-gen --\n\
         // Verify with: mise run codegen-herdr\n\
         //\n\
         // typify emits schema types in its own style; the pedantic lints\n\
         // below are expected on generated output and must be fixed in the\n\
         // generator templates, never by hand-editing the output.\n",
    );
    writeln!(
        generated,
        "#![expect(clippy::derivable_impls, clippy::clone_on_copy, clippy::must_use_candidate, clippy::default_trait_access, clippy::same_functions_in_if_condition, reason = \"typify-emitted schema types; fix the generator, not the output\")]"
    )?;
    writeln!(generated)?;
    writeln!(generated, "pub const BUNDLED_PROTOCOL: u64 = {protocol};")?;
    writeln!(
        generated,
        "pub const BUNDLED_SCHEMA_VERSION: u64 = {schema_version};"
    )?;
    writeln!(
        generated,
        "pub const BUNDLED_RAW_SCHEMA_SHA256: &str = \"{raw_provenance_sha256}\";"
    )?;
    writeln!(
        generated,
        "pub const BUNDLED_REQUEST_SCHEMA_SHA256: &str = \"{request_schema_sha256}\";\n"
    )?;
    generated.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum MethodTransport {\n\
         \tUnary,\n\
         \tEventStream,\n\
         }\n\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct MethodMetadata {\n\
         \tpub method: &'static str,\n\
         \tpub native_type: &'static str,\n\
         \tpub params_ref: &'static str,\n\
         \tpub params_type: &'static str,\n\
         \tpub transport: MethodTransport,\n\
         }\n\n\
         pub const METHODS: &[MethodMetadata] = &[\n",
    );
    for method in &methods {
        writeln!(
            generated,
            "    MethodMetadata {{ method: {:?}, native_type: {:?}, params_ref: {:?}, params_type: {:?}, transport: MethodTransport::{:?} }},",
            method.name,
            method.native_type,
            method.params_ref,
            method.params_type,
            method.transport,
        )?;
    }
    generated.push_str(
        "];\n\n\
         pub fn method_metadata(method: &str) -> Option<&'static MethodMetadata> {\n\
         \tMETHODS.iter().find(|metadata| metadata.method == method)\n\
         }\n\n\
         pub fn metadata_for_native_type(native_type: &str) -> Option<&'static MethodMetadata> {\n\
         \tMETHODS.iter().find(|metadata| metadata.native_type == native_type)\n\
         }\n\n\
         pub mod request_types {\n",
    );
    for line in type_tokens.lines() {
        writeln!(generated, "    {line}")?;
    }
    generated.push_str("}\n");
    Ok(generated)
}

fn methods(request: &Value) -> Result<Vec<Method>> {
    let branches = request
        .get("oneOf")
        .and_then(Value::as_array)
        .ok_or_else(|| eyre::eyre!("schemas.request.oneOf must be an array"))?;
    let mut methods = Vec::with_capacity(branches.len());

    for branch in branches {
        let properties = branch
            .get("properties")
            .and_then(Value::as_object)
            .ok_or_else(|| eyre::eyre!("request branch has no properties"))?;
        let name = properties
            .get("method")
            .and_then(|method| method.get("const"))
            .and_then(Value::as_str)
            .ok_or_else(|| eyre::eyre!("request branch method must have a string const"))?;
        let params_ref = properties
            .get("params")
            .and_then(|params| params.get("$ref"))
            .and_then(Value::as_str)
            .ok_or_else(|| eyre::eyre!("request method {name:?} params must be a $ref"))?;
        let params_type = params_ref
            .rsplit('/')
            .next()
            .filter(|value| !value.is_empty())
            .ok_or_else(|| eyre::eyre!("request method {name:?} has invalid params ref"))?;
        let transport = classification::transport_for(name).ok_or_else(|| {
            eyre::eyre!(
                "request method {name:?} has no transport classification; classify it explicitly"
            )
        })?;
        methods.push(Method {
            name: name.to_owned(),
            native_type: method_to_native_type(name)?,
            params_ref: params_ref.to_owned(),
            params_type: params_type.to_owned(),
            transport,
        });
    }

    methods.sort_by(|left, right| left.name.cmp(&right.name));
    validate_reversible_unique(&methods)?;
    Ok(methods)
}

fn validate_reversible_unique(methods: &[Method]) -> Result<()> {
    let mut methods_by_native_type = BTreeMap::new();
    for method in methods {
        let decoded = native_type_to_method(&method.native_type)?;
        if decoded != method.name {
            bail!(
                "native type {:?} does not reversibly decode to Herdr method {:?}",
                method.native_type,
                method.name
            );
        }
        if let Some(existing) =
            methods_by_native_type.insert(method.native_type.as_str(), method.name.as_str())
        {
            bail!(
                "Herdr methods {existing:?} and {:?} collide at native action type {:?}",
                method.name,
                method.native_type
            );
        }
    }
    if methods.windows(2).any(|pair| pair[0].name == pair[1].name) {
        bail!("request schema contains a duplicate method name");
    }
    Ok(())
}

const NATIVE_TYPE_PREFIX: &str = "native.herdr";

fn method_to_native_type(method: &str) -> Result<String> {
    if method.is_empty() || method.split('.').any(str::is_empty) {
        bail!("Herdr method {method:?} has an empty component");
    }
    match method.rsplit_once('.') {
        Some((namespace, verb)) => Ok(format!(
            "{NATIVE_TYPE_PREFIX}.{namespace}:{}",
            verb.replace('_', "-")
        )),
        None => Ok(format!("{NATIVE_TYPE_PREFIX}:{}", method.replace('_', "-"))),
    }
}

fn native_type_to_method(native_type: &str) -> Result<String> {
    let suffix = native_type
        .strip_prefix(NATIVE_TYPE_PREFIX)
        .ok_or_else(|| {
            eyre::eyre!("native action type {native_type:?} is outside the Herdr namespace")
        })?;
    let (namespace, verb) = match suffix {
        root if root.starts_with(':') => (None, &root[1..]),
        namespaced if namespaced.starts_with('.') => {
            let (namespace, verb) = namespaced[1..].rsplit_once(':').ok_or_else(|| {
                eyre::eyre!("namespaced Herdr action type {native_type:?} has no verb separator")
            })?;
            (Some(namespace), verb)
        }
        _ => bail!("invalid Herdr native action type {native_type:?}"),
    };
    if verb.is_empty() || verb.contains('.') || verb.contains(':') {
        bail!("Herdr native action type {native_type:?} has an invalid verb");
    }
    let verb = verb.replace('-', "_");
    match namespace {
        Some(namespace)
            if !namespace.is_empty()
                && !namespace.contains(':')
                && namespace.split('.').all(|component| !component.is_empty()) =>
        {
            Ok(format!("{namespace}.{verb}"))
        }
        Some(_) => bail!("Herdr native action type {native_type:?} has an invalid namespace"),
        None => Ok(verb),
    }
}
fn generate_request_types(mut request: Value) -> Result<String> {
    rewrite_request_references(&mut request);
    let root: RootSchema = serde_json::from_value(request)
        .wrap_err("could not convert Herdr request schema to schemars RootSchema")?;
    let mut types = TypeSpace::new(&TypeSpaceSettings::default());
    types
        .add_root_schema(root)
        .wrap_err("typify could not generate Herdr request types")?;
    let syntax = syn::parse_file(&types.to_stream().to_string())
        .wrap_err("typify emitted invalid Rust for the Herdr request schema")?;
    Ok(prettyplease::unparse(&syntax))
}

fn rewrite_request_references(schema: &mut Value) {
    match schema {
        Value::Object(object) => {
            if let Some(definitions) = object.remove("$defs") {
                object.insert("definitions".to_owned(), definitions);
            }
            if let Some(Value::String(reference)) = object.get_mut("$ref") {
                if let Some(rewritten) = reference.strip_prefix("#/schemas/request/$defs/") {
                    *reference = format!("#/definitions/{rewritten}");
                }
            }
            for (keyword, value) in object {
                if keyword != "$ref" {
                    rewrite_request_references(value);
                }
            }
        }
        Value::Array(values) => {
            for value in values {
                rewrite_request_references(value);
            }
        }
        _ => {}
    }
}

fn canonical_json(value: &Value) -> Result<Vec<u8>> {
    let mut canonical = value.clone();
    sort_json(&mut canonical);
    serde_json::to_vec(&canonical).wrap_err("could not serialize canonical schema")
}

fn sort_json(value: &mut Value) {
    match value {
        Value::Object(object) => {
            let mut entries = std::mem::take(object).into_iter().collect::<Vec<_>>();
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            for (_, value) in &mut entries {
                sort_json(value);
            }
            object.extend(entries);
        }
        Value::Array(values) => {
            for value in values {
                sort_json(value);
            }
        }
        _ => {}
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("{digest:x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn native_method_names_round_trip_through_metadata() {
        for method in ["plugin.action.invoke", "server.reload_config", "ping"] {
            let native_type = method_to_native_type(method).unwrap();
            assert_eq!(native_type_to_method(&native_type).unwrap(), method);
        }
        assert_eq!(
            method_to_native_type("plugin.action.invoke").unwrap(),
            "native.herdr.plugin.action:invoke"
        );
        assert_eq!(method_to_native_type("ping").unwrap(), "native.herdr:ping");
    }

    #[test]
    fn rejects_non_reversible_method_collisions() {
        let methods = [Method {
            name: "pane.send-input".to_owned(),
            native_type: method_to_native_type("pane.send-input").unwrap(),
            params_ref: "#/schemas/request/$defs/EmptyParams".to_owned(),
            params_type: "EmptyParams".to_owned(),
            transport: Transport::Unary,
        }];
        let error = validate_reversible_unique(&methods).unwrap_err();
        assert!(error.to_string().contains("reversibly decode"));
    }

    #[test]
    fn canonicalization_sorts_nested_object_keys() {
        let input = serde_json::json!({"b": {"z": 1, "a": 2}, "a": true});
        assert_eq!(
            String::from_utf8(canonical_json(&input).unwrap()).unwrap(),
            r#"{"a":true,"b":{"a":2,"z":1}}"#,
        );
    }

    #[test]
    fn rewrites_only_ref_keyword_values() {
        let mut schema = serde_json::json!({
            "$defs": {"Thing": {"type": "string"}},
            "$ref": "#/schemas/request/$defs/Thing",
            "description": "#/schemas/request/$defs/Thing",
            "const": "#/schemas/request/$defs/Thing",
        });
        rewrite_request_references(&mut schema);
        assert_eq!(schema["$ref"], "#/definitions/Thing");
        assert_eq!(schema["description"], "#/schemas/request/$defs/Thing");
        assert_eq!(schema["const"], "#/schemas/request/$defs/Thing");
        assert!(schema.get("$defs").is_none());
        assert!(schema.get("definitions").is_some());
    }
}
