// @generated by tools/muxe-zellij-gen; do not edit by hand.
// Regenerate with: cargo run --locked -p muxe-zellij-gen --
// Integration requires serde, serde_json, and the pinned zellij-utils crate.

pub const PINNED_ZELLIJ_REVISION: &str = "af38660c5884f50bb3726682fb92961326c4268f";
pub const PINNED_ZELLIJ_VERSION: &str = "0.46.0";

pub const SOURCE_INPUT_SHA256: &[(&str, &str)] = &[
    ("zellij-client/src/cli_client.rs", "73d59993a56e4ea9dfe518de93a7c5ad74e8b3e98027bcef54944721f16897d8"),
    ("zellij-server/src/panes/grid.rs", "ef99f9a55840ef91d453bce6050facfa8ae5ca2edee43f96c65929fac710d047"),
    ("zellij-server/src/panes/terminal_pane.rs", "5f0903629b3eb662ef27a3be992c111c8241d23f502506536950509da4e75841"),
    ("zellij-server/src/route.rs", "773583abd400674e7e64970f138655e83a35f53aabb8164b0cb40c755f47b5b3"),
    ("zellij-tile/src/shim.rs", "219ecb24b870d9ae4fbf14ee87f09813d602150e5bb4f18c7f901c5ca3434adc"),
    ("zellij-utils/src/data.rs", "03b38140c1e3dc097c4acabb9b80f6561205fefc0f7da8f29b4eba36000beb06"),
    ("zellij-utils/src/input/actions.rs", "660f4cf4f3da51bd4cf7cc90871aed90300ba81c203b9528df1a6ff2af4fdee5"),
    ("zellij-utils/src/input/command.rs", "bf3aec90d4b0379493b76b57d51ccf8d757f6463171b090b8eb5a62b6c462a98"),
    ("zellij-utils/src/input/layout.rs", "868e1987b1824b42ae04ec5d6765b09a6516c86abb5239d6614b837e114400b3"),
    ("zellij-utils/src/input/mouse.rs", "69ca86fedf70fb2aaac97ed8de58e9d08579dd9a38a2cef0da64d2158f7d608f"),
    ("zellij-utils/src/input/options.rs", "573517e549d61fe0e98c52b57ec9a1feac331c1fb4bb869b5b2ab39e0dd2a2b0"),
    ("zellij-utils/src/plugin_api/action.proto", "0ce47a2b3a65735835c094ac13e96fa5c70db0e6993a71c6dc076f91a5dd20dc"),
    ("zellij-utils/src/plugin_api/plugin_command.proto", "cd02e56acd6389bfee21be9b6a91a493178f2d948ab9847f4c3e84e1470c9da0"),
    ("zellij-utils/src/position.rs", "344b13ced07f89c43d47753cb5b99bd895eab767e53e83e566f7a44254bba43d"),
];

pub const MIRROR_TYPE_SOURCES: &[(&str, &str)] = &[
    ("Action", "zellij-utils/src/input/actions.rs"),
    ("BareKey", "zellij-utils/src/data.rs"),
    ("ClientId", "zellij-utils/src/data.rs"),
    ("Column", "zellij-utils/src/position.rs"),
    ("CommandOrPlugin", "zellij-utils/src/data.rs"),
    ("Context", "zellij-utils/src/data.rs"),
    ("Direction", "zellij-utils/src/data.rs"),
    ("FileToOpen", "zellij-utils/src/data.rs"),
    ("FloatingPaneCoordinates", "zellij-utils/src/data.rs"),
    ("FloatingPaneLayout", "zellij-utils/src/input/layout.rs"),
    ("InputMode", "zellij-utils/src/data.rs"),
    ("KeyModifier", "zellij-utils/src/data.rs"),
    ("KeyWithModifier", "zellij-utils/src/data.rs"),
    ("LayoutConstraint", "zellij-utils/src/input/layout.rs"),
    ("LayoutInfo", "zellij-utils/src/data.rs"),
    ("LayoutMetadata", "zellij-utils/src/data.rs"),
    ("Line", "zellij-utils/src/position.rs"),
    ("MouseEvent", "zellij-utils/src/input/mouse.rs"),
    ("MouseEventType", "zellij-utils/src/input/mouse.rs"),
    ("NewPanePlacement", "zellij-utils/src/data.rs"),
    ("OpenFilePayload", "zellij-utils/src/input/command.rs"),
    ("OriginatingPlugin", "zellij-utils/src/data.rs"),
    ("PaneFrameStyle", "zellij-utils/src/input/options.rs"),
    ("PaneId", "zellij-utils/src/data.rs"),
    ("PaneMetadata", "zellij-utils/src/data.rs"),
    ("PercentOrFixed", "zellij-utils/src/input/layout.rs"),
    ("PluginAlias", "zellij-utils/src/input/layout.rs"),
    ("PluginTag", "zellij-utils/src/data.rs"),
    ("PluginUserConfiguration", "zellij-utils/src/input/layout.rs"),
    ("Position", "zellij-utils/src/position.rs"),
    ("Resize", "zellij-utils/src/data.rs"),
    ("Run", "zellij-utils/src/input/layout.rs"),
    ("RunCommand", "zellij-utils/src/input/command.rs"),
    ("RunCommandAction", "zellij-utils/src/input/command.rs"),
    ("RunPlugin", "zellij-utils/src/input/layout.rs"),
    ("RunPluginLocation", "zellij-utils/src/input/layout.rs"),
    ("RunPluginOrAlias", "zellij-utils/src/input/layout.rs"),
    ("SearchDirection", "zellij-utils/src/input/actions.rs"),
    ("SearchOption", "zellij-utils/src/input/actions.rs"),
    ("SplitDirection", "zellij-utils/src/input/layout.rs"),
    ("SplitSize", "zellij-utils/src/input/layout.rs"),
    ("SwapFloatingLayout", "zellij-utils/src/input/layout.rs"),
    ("SwapTiledLayout", "zellij-utils/src/input/layout.rs"),
    ("TabLayoutInfo", "zellij-utils/src/input/layout.rs"),
    ("TabMetadata", "zellij-utils/src/data.rs"),
    ("TiledPaneLayout", "zellij-utils/src/input/layout.rs"),
    ("UnblockCondition", "zellij-utils/src/data.rs"),
];

pub const ACTION_VARIANTS: &[(&str, &[&str])] = &[
    ("AreFloatingPanesVisible", &["tab_id: Option < usize >", ]),
    ("BreakPane", &[]),
    ("BreakPaneLeft", &[]),
    ("BreakPaneRight", &[]),
    ("ChangeFloatingPaneCoordinates", &["pane_id: PaneId", "coordinates: FloatingPaneCoordinates", ]),
    ("ClearScreen", &[]),
    ("ClearScreenByPaneId", &["pane_id: PaneId", ]),
    ("CliPipe", &["pipe_id: String", "name: Option < String >", "payload: Option < String >", "args: Option < BTreeMap < String , String > >", "plugin: Option < String >", "configuration: Option < BTreeMap < String , String > >", "launch_new: bool", "skip_cache: bool", "floating: Option < bool >", "in_place: Option < bool >", "cwd: Option < PathBuf >", "pane_title: Option < String >", ]),
    ("CloseFocus", &[]),
    ("CloseFocusByPaneId", &["pane_id: PaneId", ]),
    ("ClosePluginPane", &["pane_id: u32", ]),
    ("CloseTab", &[]),
    ("CloseTabById", &["id: u64", ]),
    ("CloseTerminalPane", &["pane_id: u32", ]),
    ("Confirm", &[]),
    ("Copy", &[]),
    ("CopyLastCommandOutput", &[]),
    ("CurrentTabInfo", &["output_json: bool", ]),
    ("Deny", &[]),
    ("Detach", &[]),
    ("DumpLayout", &[]),
    ("DumpScreen", &["file_path: Option < String >", "include_scrollback: bool", "pane_id: Option < PaneId >", "ansi: bool", ]),
    ("EditFile", &["payload: OpenFilePayload", "direction: Option < Direction >", "floating: bool", "in_place: bool", "close_replaced_pane: bool", "start_suppressed: bool", "coordinates: Option < FloatingPaneCoordinates >", "near_current_pane: bool", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("EditScrollback", &["ansi: bool", ]),
    ("EditScrollbackByPaneId", &["pane_id: PaneId", "ansi: bool", ]),
    ("FocusGuestSession", &[]),
    ("FocusHostSession", &[]),
    ("FocusLastPane", &[]),
    ("FocusNextPane", &[]),
    ("FocusPaneByPaneId", &["pane_id: PaneId", ]),
    ("FocusPluginPaneWithId", &["pane_id: u32", "should_float_if_hidden: bool", "should_be_in_place_if_hidden: bool", ]),
    ("FocusPreviousPane", &[]),
    ("FocusTerminalPaneWithId", &["pane_id: u32", "should_float_if_hidden: bool", "should_be_in_place_if_hidden: bool", ]),
    ("GoToNextTab", &[]),
    ("GoToPreviousTab", &[]),
    ("GoToTab", &["index: u32", ]),
    ("GoToTabById", &["id: u64", ]),
    ("GoToTabName", &["name: String", "create: bool", ]),
    ("HalfPageScrollDown", &[]),
    ("HalfPageScrollDownByPaneId", &["pane_id: PaneId", ]),
    ("HalfPageScrollUp", &[]),
    ("HalfPageScrollUpByPaneId", &["pane_id: PaneId", ]),
    ("HideFloatingPanes", &["tab_id: Option < usize >", ]),
    ("KeybindPipe", &["name: Option < String >", "payload: Option < String >", "args: Option < BTreeMap < String , String > >", "plugin: Option < String >", "plugin_id: Option < u32 >", "configuration: Option < BTreeMap < String , String > >", "launch_new: bool", "skip_cache: bool", "floating: Option < bool >", "in_place: Option < bool >", "cwd: Option < PathBuf >", "pane_title: Option < String >", ]),
    ("LaunchOrFocusPlugin", &["plugin: RunPluginOrAlias", "should_float: bool", "move_to_focused_tab: bool", "should_open_in_place: bool", "close_replaced_pane: bool", "skip_cache: bool", "tab_id: Option < usize >", ]),
    ("LaunchPlugin", &["plugin: RunPluginOrAlias", "should_float: bool", "should_open_in_place: bool", "close_replaced_pane: bool", "skip_cache: bool", "cwd: Option < PathBuf >", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("ListClients", &[]),
    ("ListPanes", &["show_tab: bool", "show_command: bool", "show_state: bool", "show_geometry: bool", "show_all: bool", "output_json: bool", ]),
    ("ListTabs", &["show_state: bool", "show_dimensions: bool", "show_panes: bool", "show_layout: bool", "show_all: bool", "output_json: bool", ]),
    ("MouseEvent", &["event: MouseEvent", ]),
    ("MoveFocus", &["direction: Direction", ]),
    ("MoveFocusOrTab", &["direction: Direction", ]),
    ("MovePane", &["direction: Option < Direction >", ]),
    ("MovePaneBackwards", &[]),
    ("MovePaneBackwardsByPaneId", &["pane_id: PaneId", ]),
    ("MovePaneByPaneId", &["pane_id: PaneId", "direction: Option < Direction >", ]),
    ("MoveTab", &["direction: Direction", ]),
    ("MoveTabByTabId", &["id: u64", "direction: Direction", ]),
    ("NewBlockingPane", &["placement: NewPanePlacement", "pane_name: Option < String >", "command: Option < RunCommandAction >", "unblock_condition: Option < UnblockCondition >", "near_current_pane: bool", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NewFloatingPane", &["command: Option < RunCommandAction >", "pane_name: Option < String >", "coordinates: Option < FloatingPaneCoordinates >", "near_current_pane: bool", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NewFloatingPluginPane", &["plugin: RunPluginOrAlias", "pane_name: Option < String >", "skip_cache: bool", "cwd: Option < PathBuf >", "coordinates: Option < FloatingPaneCoordinates >", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NewInPlacePane", &["command: Option < RunCommandAction >", "pane_name: Option < String >", "near_current_pane: bool", "no_focus: bool", "pane_id_to_replace: Option < PaneId >", "close_replaced_pane: bool", "tab_id: Option < usize >", ]),
    ("NewInPlacePluginPane", &["plugin: RunPluginOrAlias", "pane_name: Option < String >", "skip_cache: bool", "close_replaced_pane: bool", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NewPane", &["direction: Option < Direction >", "pane_name: Option < String >", "start_suppressed: bool", ]),
    ("NewStackedPane", &["command: Option < RunCommandAction >", "pane_name: Option < String >", "near_current_pane: bool", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NewTab", &["tiled_layout: Option < TiledPaneLayout >", "floating_layouts: Vec < FloatingPaneLayout >", "swap_tiled_layouts: Option < Vec < SwapTiledLayout > >", "swap_floating_layouts: Option < Vec < SwapFloatingLayout > >", "tab_name: Option < String >", "should_change_focus_to_new_tab: bool", "cwd: Option < PathBuf >", "initial_panes: Option < Vec < CommandOrPlugin > >", "first_pane_unblock_condition: Option < UnblockCondition >", ]),
    ("NewTiledPane", &["direction: Option < Direction >", "command: Option < RunCommandAction >", "pane_name: Option < String >", "near_current_pane: bool", "no_focus: bool", "borderless: Option < bool >", "tab_id: Option < usize >", ]),
    ("NewTiledPluginPane", &["plugin: RunPluginOrAlias", "pane_name: Option < String >", "skip_cache: bool", "cwd: Option < PathBuf >", "no_focus: bool", "tab_id: Option < usize >", ]),
    ("NextSwapLayout", &[]),
    ("NextSwapLayoutByTabId", &["id: u64", ]),
    ("NoOp", &[]),
    ("OverrideLayout", &["tabs: Vec < TabLayoutInfo >", "retain_existing_terminal_panes: bool", "retain_existing_plugin_panes: bool", "apply_only_to_active_tab: bool", ]),
    ("PageScrollDown", &[]),
    ("PageScrollDownByPaneId", &["pane_id: PaneId", ]),
    ("PageScrollUp", &[]),
    ("PageScrollUpByPaneId", &["pane_id: PaneId", ]),
    ("PaneNameInput", &["input: Vec < u8 >", ]),
    ("Paste", &["chars: String", "pane_id: Option < PaneId >", ]),
    ("PreviousSwapLayout", &[]),
    ("PreviousSwapLayoutByTabId", &["id: u64", ]),
    ("QueryTabNames", &[]),
    ("Quit", &[]),
    ("RenamePaneByPaneId", &["pane_id: Option < PaneId >", "name: Vec < u8 >", ]),
    ("RenamePluginPane", &["pane_id: u32", "name: Vec < u8 >", ]),
    ("RenameSession", &["name: String", ]),
    ("RenameTab", &["tab_index: u32", "name: Vec < u8 >", ]),
    ("RenameTabById", &["id: u64", "name: String", ]),
    ("RenameTerminalPane", &["pane_id: u32", "name: Vec < u8 >", ]),
    ("Resize", &["resize: Resize", "direction: Option < Direction >", ]),
    ("ResizeByPaneId", &["pane_id: PaneId", "resize: Resize", "direction: Option < Direction >", ]),
    ("Run", &["command: RunCommandAction", "near_current_pane: bool", "no_focus: bool", ]),
    ("SaveSession", &[]),
    ("ScrollDown", &[]),
    ("ScrollDownAt", &["position: Position", ]),
    ("ScrollDownByPaneId", &["pane_id: PaneId", ]),
    ("ScrollToBottom", &[]),
    ("ScrollToBottomByPaneId", &["pane_id: PaneId", ]),
    ("ScrollToNextPrompt", &[]),
    ("ScrollToPreviousPrompt", &[]),
    ("ScrollToTop", &[]),
    ("ScrollToTopByPaneId", &["pane_id: PaneId", ]),
    ("ScrollUp", &[]),
    ("ScrollUpAt", &["position: Position", ]),
    ("ScrollUpByPaneId", &["pane_id: PaneId", ]),
    ("Search", &["direction: SearchDirection", ]),
    ("SearchInput", &["input: Vec < u8 >", ]),
    ("SearchToggleOption", &["option: SearchOption", ]),
    ("SelectCommandAtScrollPosition", &[]),
    ("SetDarkTheme", &[]),
    ("SetLightTheme", &[]),
    ("SetPaneBorderless", &["pane_id: PaneId", "borderless: bool", ]),
    ("SetPaneColor", &["pane_id: PaneId", "fg: Option < String >", "bg: Option < String >", ]),
    ("SetPaneFrameStyle", &["PaneFrameStyle", ]),
    ("ShowFloatingPanes", &["tab_id: Option < usize >", ]),
    ("SkipConfirm", &["action: Box < Action >", ]),
    ("StackPanes", &["pane_ids: Vec < PaneId >", ]),
    ("StartOrReloadPlugin", &["plugin: RunPluginOrAlias", ]),
    ("SwitchFocus", &[]),
    ("SwitchModeForAllClients", &["input_mode: InputMode", ]),
    ("SwitchSession", &["name: String", "tab_position: Option < usize >", "pane_id: Option < (u32 , bool) >", "layout: Option < LayoutInfo >", "cwd: Option < PathBuf >", ]),
    ("SwitchToMode", &["input_mode: InputMode", ]),
    ("TabNameInput", &["input: Vec < u8 >", ]),
    ("ToggleActiveSyncTab", &[]),
    ("ToggleActiveSyncTabByTabId", &["id: u64", ]),
    ("ToggleFloatingPanes", &[]),
    ("ToggleFloatingPanesByTabId", &["id: u64", ]),
    ("ToggleFocusFullscreen", &[]),
    ("ToggleFocusFullscreenByPaneId", &["pane_id: PaneId", ]),
    ("ToggleFocusNoUiFullscreen", &[]),
    ("ToggleFocusNoUiFullscreenByPaneId", &["pane_id: PaneId", ]),
    ("ToggleGroupMarking", &[]),
    ("ToggleHostFullscreen", &[]),
    ("ToggleMouseMode", &[]),
    ("TogglePaneBorderless", &["pane_id: PaneId", ]),
    ("TogglePaneEmbedOrFloating", &[]),
    ("TogglePaneEmbedOrFloatingByPaneId", &["pane_id: PaneId", ]),
    ("TogglePaneFrames", &[]),
    ("TogglePaneInGroup", &[]),
    ("TogglePanePinned", &[]),
    ("TogglePanePinnedByPaneId", &["pane_id: PaneId", ]),
    ("ToggleTab", &[]),
    ("ToggleTheme", &[]),
    ("UndoRenamePane", &[]),
    ("UndoRenamePaneByPaneId", &["pane_id: PaneId", ]),
    ("UndoRenameTab", &[]),
    ("UndoRenameTabByTabId", &["id: u64", ]),
    ("Write", &["key_with_modifier: Option < KeyWithModifier >", "bytes: Vec < u8 >", "is_kitty_keyboard_protocol: bool", ]),
    ("WriteChars", &["chars: String", ]),
    ("WriteCharsToPaneId", &["chars: String", "pane_id: PaneId", ]),
    ("WriteToPaneId", &["bytes: Vec < u8 >", "pane_id: PaneId", ]),
];

pub const ACTION_CONVERTERS: &[(&str, &str)] = &[
    ("Action", "mirror"),
    ("CommandOrPlugin", "mirror"),
    ("Direction", "mirror"),
    ("FloatingPaneCoordinates", "mirror"),
    ("FloatingPaneLayout", "mirror"),
    ("InputMode", "mirror"),
    ("KeyWithModifier", "mirror"),
    ("LayoutInfo", "mirror"),
    ("MouseEvent", "mirror"),
    ("NewPanePlacement", "mirror"),
    ("OpenFilePayload", "mirror"),
    ("PaneFrameStyle", "mirror"),
    ("PaneId", "mirror"),
    ("PathBuf", "builtin"),
    ("Position", "mirror"),
    ("Resize", "mirror"),
    ("RunCommandAction", "mirror"),
    ("RunPluginOrAlias", "mirror"),
    ("SearchDirection", "mirror"),
    ("SearchOption", "mirror"),
    ("SwapFloatingLayout", "mirror"),
    ("SwapTiledLayout", "mirror"),
    ("TabLayoutInfo", "mirror"),
    ("TiledPaneLayout", "mirror"),
    ("UnblockCondition", "mirror"),
];

pub const PUBLIC_PLUGIN_FUNCTIONS: &[(&str, &str)] = &[
    ("block_cli_pipe_input", "internal"),
    ("break_panes_to_new_tab", "unsupported"),
    ("break_panes_to_tab_with_id", "unsupported"),
    ("break_panes_to_tab_with_index", "unsupported"),
    ("bytes_from_stdin", "unsupported"),
    ("change_floating_panes_coordinates", "unsupported"),
    ("change_host_folder", "unsupported"),
    ("clear_key_presses_intercepts", "unsupported"),
    ("clear_pane_highlights", "unsupported"),
    ("clear_screen", "unsupported"),
    ("clear_screen_for_pane_id", "unsupported"),
    ("cli_pipe_output", "internal"),
    ("close_focus", "unsupported"),
    ("close_focused_tab", "unsupported"),
    ("close_multiple_panes", "unsupported"),
    ("close_pane_with_id", "unsupported"),
    ("close_plugin_pane", "unsupported"),
    ("close_self", "unsupported"),
    ("close_tab_with_id", "unsupported"),
    ("close_tab_with_index", "unsupported"),
    ("close_terminal_pane", "unsupported"),
    ("copy_to_clipboard", "unsupported"),
    ("current_session_last_saved_time", "unsupported"),
    ("delete_all_dead_sessions", "unsupported"),
    ("delete_dead_session", "unsupported"),
    ("delete_layout", "unsupported"),
    ("detach", "unsupported"),
    ("disconnect_other_clients", "unsupported"),
    ("dump_layout", "unsupported"),
    ("dump_session_layout", "unsupported"),
    ("dump_session_layout_for_tab", "unsupported"),
    ("edit_layout", "unsupported"),
    ("edit_scrollback", "unsupported"),
    ("edit_scrollback_for_pane_with_id", "unsupported"),
    ("embed_multiple_panes", "unsupported"),
    ("exec_cmd", "unsupported"),
    ("float_multiple_panes", "unsupported"),
    ("focus_host_session", "unsupported"),
    ("focus_last_pane", "unsupported"),
    ("focus_next_pane", "unsupported"),
    ("focus_or_create_tab", "unsupported"),
    ("focus_pane_with_id", "unsupported"),
    ("focus_plugin_pane", "unsupported"),
    ("focus_previous_pane", "unsupported"),
    ("focus_terminal_pane", "unsupported"),
    ("generate_random_name", "unsupported"),
    ("generate_web_login_token", "unsupported"),
    ("get_focused_pane", "unsupported"),
    ("get_focused_pane_info", "unsupported"),
    ("get_focused_tab", "unsupported"),
    ("get_layout_dir", "unsupported"),
    ("get_pane_cwd", "unsupported"),
    ("get_pane_info", "unsupported"),
    ("get_pane_pid", "unsupported"),
    ("get_pane_running_command", "unsupported"),
    ("get_pane_scrollback", "unsupported"),
    ("get_plugin_ids", "internal"),
    ("get_session_environment_variables", "unsupported"),
    ("get_session_list", "unsupported"),
    ("get_tab_info", "unsupported"),
    ("get_zellij_version", "unsupported"),
    ("go_to_next_tab", "unsupported"),
    ("go_to_previous_tab", "unsupported"),
    ("go_to_tab", "unsupported"),
    ("go_to_tab_name", "unsupported"),
    ("group_and_ungroup_panes", "unsupported"),
    ("hide_floating_panes", "unsupported"),
    ("hide_pane_with_id", "unsupported"),
    ("hide_self", "unsupported"),
    ("highlight_and_unhighlight_panes", "unsupported"),
    ("intercept_key_presses", "unsupported"),
    ("kill_sessions", "unsupported"),
    ("list_clients", "internal"),
    ("list_web_login_tokens", "unsupported"),
    ("list_windows_volumes", "unsupported"),
    ("load_new_plugin", "unsupported"),
    ("move_focus", "unsupported"),
    ("move_focus_or_tab", "unsupported"),
    ("move_pane", "unsupported"),
    ("move_pane_with_direction", "unsupported"),
    ("move_pane_with_pane_id", "unsupported"),
    ("move_pane_with_pane_id_in_direction", "unsupported"),
    ("new_pane", "unsupported"),
    ("new_tab", "unsupported"),
    ("new_tab_unfocused", "unsupported"),
    ("new_tabs_with_layout", "unsupported"),
    ("new_tabs_with_layout_info", "unsupported"),
    ("new_tiled_pane_in_tab", "unsupported"),
    ("next_swap_layout", "unsupported"),
    ("object_from_stdin", "unsupported"),
    ("object_to_stdout", "unsupported"),
    ("open_command_pane", "unsupported"),
    ("open_command_pane_background", "unsupported"),
    ("open_command_pane_floating", "unsupported"),
    ("open_command_pane_floating_near_plugin", "unsupported"),
    ("open_command_pane_in_new_tab", "unsupported"),
    ("open_command_pane_in_place", "unsupported"),
    ("open_command_pane_in_place_of_pane_id", "unsupported"),
    ("open_command_pane_in_place_of_plugin", "unsupported"),
    ("open_command_pane_near_plugin", "unsupported"),
    ("open_edit_pane_in_place_of_pane_id", "unsupported"),
    ("open_editor_pane_in_new_tab", "unsupported"),
    ("open_file", "unsupported"),
    ("open_file_floating", "unsupported"),
    ("open_file_floating_near_plugin", "unsupported"),
    ("open_file_in_place", "unsupported"),
    ("open_file_in_place_of_plugin", "unsupported"),
    ("open_file_near_plugin", "unsupported"),
    ("open_plugin_pane_floating", "unsupported"),
    ("open_plugin_pane_in_new_tab", "unsupported"),
    ("open_terminal", "unsupported"),
    ("open_terminal_floating", "unsupported"),
    ("open_terminal_floating_near_plugin", "unsupported"),
    ("open_terminal_in_place", "unsupported"),
    ("open_terminal_in_place_of_plugin", "unsupported"),
    ("open_terminal_near_plugin", "unsupported"),
    ("open_terminal_pane_in_place_of_pane_id", "unsupported"),
    ("override_layout", "unsupported"),
    ("page_scroll_down", "unsupported"),
    ("page_scroll_down_in_pane_id", "unsupported"),
    ("page_scroll_up", "unsupported"),
    ("page_scroll_up_in_pane_id", "unsupported"),
    ("parse_layout", "unsupported"),
    ("pipe_message_to_plugin", "unsupported"),
    ("post_message_to", "unsupported"),
    ("post_message_to_plugin", "unsupported"),
    ("previous_swap_layout", "unsupported"),
    ("query_web_server_status", "unsupported"),
    ("quit_zellij", "unsupported"),
    ("rebind_keys", "unsupported"),
    ("reconfigure", "unsupported"),
    ("reload_plugin_with_id", "unsupported"),
    ("rename_layout", "unsupported"),
    ("rename_pane_with_id", "unsupported"),
    ("rename_plugin_pane", "unsupported"),
    ("rename_session", "unsupported"),
    ("rename_tab", "unsupported"),
    ("rename_tab_with_id", "unsupported"),
    ("rename_terminal_pane", "unsupported"),
    ("rename_web_token", "unsupported"),
    ("replace_pane_with_existing_pane", "unsupported"),
    ("report_panic", "unsupported"),
    ("request_permission", "internal"),
    ("rerun_command_pane", "unsupported"),
    ("resize_focused_pane", "unsupported"),
    ("resize_focused_pane_with_direction", "unsupported"),
    ("resize_pane_with_id", "unsupported"),
    ("revoke_all_web_tokens", "unsupported"),
    ("revoke_web_login_token", "unsupported"),
    ("run_action", "exposed"),
    ("run_command", "unsupported"),
    ("run_command_with_env_variables_and_cwd", "unsupported"),
    ("save_layout", "unsupported"),
    ("save_session", "unsupported"),
    ("scan_host_folder", "unsupported"),
    ("scroll_down", "unsupported"),
    ("scroll_down_in_pane_id", "unsupported"),
    ("scroll_to_bottom", "unsupported"),
    ("scroll_to_bottom_in_pane_id", "unsupported"),
    ("scroll_to_top", "unsupported"),
    ("scroll_to_top_in_pane_id", "unsupported"),
    ("scroll_up", "unsupported"),
    ("scroll_up_in_pane_id", "unsupported"),
    ("send_sigint_to_pane_id", "unsupported"),
    ("send_sigkill_to_pane_id", "unsupported"),
    ("set_floating_pane_pinned", "unsupported"),
    ("set_pane_borderless", "unsupported"),
    ("set_pane_color", "unsupported"),
    ("set_pane_frame_style", "unsupported"),
    ("set_pane_regex_highlights", "unsupported"),
    ("set_selectable", "unsupported"),
    ("set_self_mouse_selection_support", "unsupported"),
    ("set_soft_keyboard", "unsupported"),
    ("set_timeout", "unsupported"),
    ("share_current_session", "unsupported"),
    ("show_cursor", "unsupported"),
    ("show_floating_panes", "unsupported"),
    ("show_pane_with_id", "unsupported"),
    ("show_self", "unsupported"),
    ("stack_panes", "unsupported"),
    ("start_or_reload_plugin", "unsupported"),
    ("start_web_server", "unsupported"),
    ("stop_sharing_current_session", "unsupported"),
    ("stop_web_server", "unsupported"),
    ("subscribe", "internal"),
    ("switch_session", "unsupported"),
    ("switch_session_with_cwd", "unsupported"),
    ("switch_session_with_focus", "unsupported"),
    ("switch_session_with_layout", "unsupported"),
    ("switch_tab_to", "unsupported"),
    ("switch_to_input_mode", "internal"),
    ("toggle_active_tab_sync", "unsupported"),
    ("toggle_floating_panes", "unsupported"),
    ("toggle_focus_fullscreen", "unsupported"),
    ("toggle_focus_no_ui_fullscreen", "unsupported"),
    ("toggle_pane_borderless", "unsupported"),
    ("toggle_pane_embed_or_eject", "unsupported"),
    ("toggle_pane_embed_or_eject_for_pane_id", "unsupported"),
    ("toggle_pane_frames", "unsupported"),
    ("toggle_pane_id_fullscreen", "unsupported"),
    ("toggle_tab", "unsupported"),
    ("unblock_cli_pipe_input", "internal"),
    ("undo_rename_pane", "unsupported"),
    ("undo_rename_tab", "unsupported"),
    ("unsubscribe", "internal"),
    ("watch_filesystem", "unsupported"),
    ("web_request", "unsupported"),
    ("write", "unsupported"),
    ("write_chars", "unsupported"),
    ("write_chars_to_pane_id", "unsupported"),
    ("write_to_pane_id", "unsupported"),
];

pub const UNSUPPORTED_PUBLIC_PLUGIN_FUNCTIONS: &[&str] = &[
    "break_panes_to_new_tab",
    "break_panes_to_tab_with_id",
    "break_panes_to_tab_with_index",
    "bytes_from_stdin",
    "change_floating_panes_coordinates",
    "change_host_folder",
    "clear_key_presses_intercepts",
    "clear_pane_highlights",
    "clear_screen",
    "clear_screen_for_pane_id",
    "close_focus",
    "close_focused_tab",
    "close_multiple_panes",
    "close_pane_with_id",
    "close_plugin_pane",
    "close_self",
    "close_tab_with_id",
    "close_tab_with_index",
    "close_terminal_pane",
    "copy_to_clipboard",
    "current_session_last_saved_time",
    "delete_all_dead_sessions",
    "delete_dead_session",
    "delete_layout",
    "detach",
    "disconnect_other_clients",
    "dump_layout",
    "dump_session_layout",
    "dump_session_layout_for_tab",
    "edit_layout",
    "edit_scrollback",
    "edit_scrollback_for_pane_with_id",
    "embed_multiple_panes",
    "exec_cmd",
    "float_multiple_panes",
    "focus_host_session",
    "focus_last_pane",
    "focus_next_pane",
    "focus_or_create_tab",
    "focus_pane_with_id",
    "focus_plugin_pane",
    "focus_previous_pane",
    "focus_terminal_pane",
    "generate_random_name",
    "generate_web_login_token",
    "get_focused_pane",
    "get_focused_pane_info",
    "get_focused_tab",
    "get_layout_dir",
    "get_pane_cwd",
    "get_pane_info",
    "get_pane_pid",
    "get_pane_running_command",
    "get_pane_scrollback",
    "get_session_environment_variables",
    "get_session_list",
    "get_tab_info",
    "get_zellij_version",
    "go_to_next_tab",
    "go_to_previous_tab",
    "go_to_tab",
    "go_to_tab_name",
    "group_and_ungroup_panes",
    "hide_floating_panes",
    "hide_pane_with_id",
    "hide_self",
    "highlight_and_unhighlight_panes",
    "intercept_key_presses",
    "kill_sessions",
    "list_web_login_tokens",
    "list_windows_volumes",
    "load_new_plugin",
    "move_focus",
    "move_focus_or_tab",
    "move_pane",
    "move_pane_with_direction",
    "move_pane_with_pane_id",
    "move_pane_with_pane_id_in_direction",
    "new_pane",
    "new_tab",
    "new_tab_unfocused",
    "new_tabs_with_layout",
    "new_tabs_with_layout_info",
    "new_tiled_pane_in_tab",
    "next_swap_layout",
    "object_from_stdin",
    "object_to_stdout",
    "open_command_pane",
    "open_command_pane_background",
    "open_command_pane_floating",
    "open_command_pane_floating_near_plugin",
    "open_command_pane_in_new_tab",
    "open_command_pane_in_place",
    "open_command_pane_in_place_of_pane_id",
    "open_command_pane_in_place_of_plugin",
    "open_command_pane_near_plugin",
    "open_edit_pane_in_place_of_pane_id",
    "open_editor_pane_in_new_tab",
    "open_file",
    "open_file_floating",
    "open_file_floating_near_plugin",
    "open_file_in_place",
    "open_file_in_place_of_plugin",
    "open_file_near_plugin",
    "open_plugin_pane_floating",
    "open_plugin_pane_in_new_tab",
    "open_terminal",
    "open_terminal_floating",
    "open_terminal_floating_near_plugin",
    "open_terminal_in_place",
    "open_terminal_in_place_of_plugin",
    "open_terminal_near_plugin",
    "open_terminal_pane_in_place_of_pane_id",
    "override_layout",
    "page_scroll_down",
    "page_scroll_down_in_pane_id",
    "page_scroll_up",
    "page_scroll_up_in_pane_id",
    "parse_layout",
    "pipe_message_to_plugin",
    "post_message_to",
    "post_message_to_plugin",
    "previous_swap_layout",
    "query_web_server_status",
    "quit_zellij",
    "rebind_keys",
    "reconfigure",
    "reload_plugin_with_id",
    "rename_layout",
    "rename_pane_with_id",
    "rename_plugin_pane",
    "rename_session",
    "rename_tab",
    "rename_tab_with_id",
    "rename_terminal_pane",
    "rename_web_token",
    "replace_pane_with_existing_pane",
    "report_panic",
    "rerun_command_pane",
    "resize_focused_pane",
    "resize_focused_pane_with_direction",
    "resize_pane_with_id",
    "revoke_all_web_tokens",
    "revoke_web_login_token",
    "run_command",
    "run_command_with_env_variables_and_cwd",
    "save_layout",
    "save_session",
    "scan_host_folder",
    "scroll_down",
    "scroll_down_in_pane_id",
    "scroll_to_bottom",
    "scroll_to_bottom_in_pane_id",
    "scroll_to_top",
    "scroll_to_top_in_pane_id",
    "scroll_up",
    "scroll_up_in_pane_id",
    "send_sigint_to_pane_id",
    "send_sigkill_to_pane_id",
    "set_floating_pane_pinned",
    "set_pane_borderless",
    "set_pane_color",
    "set_pane_frame_style",
    "set_pane_regex_highlights",
    "set_selectable",
    "set_self_mouse_selection_support",
    "set_soft_keyboard",
    "set_timeout",
    "share_current_session",
    "show_cursor",
    "show_floating_panes",
    "show_pane_with_id",
    "show_self",
    "stack_panes",
    "start_or_reload_plugin",
    "start_web_server",
    "stop_sharing_current_session",
    "stop_web_server",
    "switch_session",
    "switch_session_with_cwd",
    "switch_session_with_focus",
    "switch_session_with_layout",
    "switch_tab_to",
    "toggle_active_tab_sync",
    "toggle_floating_panes",
    "toggle_focus_fullscreen",
    "toggle_focus_no_ui_fullscreen",
    "toggle_pane_borderless",
    "toggle_pane_embed_or_eject",
    "toggle_pane_embed_or_eject_for_pane_id",
    "toggle_pane_frames",
    "toggle_pane_id_fullscreen",
    "toggle_tab",
    "undo_rename_pane",
    "undo_rename_tab",
    "watch_filesystem",
    "web_request",
    "write",
    "write_chars",
    "write_chars_to_pane_id",
    "write_to_pane_id",
];

pub mod action_mirror {
    use serde::{Deserialize, Serialize};
    use std::{collections::{BTreeMap, BTreeSet}, path::PathBuf};

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum Action {
        Quit,
        Write {
            key_with_modifier: Option < KeyWithModifier >,
            bytes: Vec < u8 >,
            is_kitty_keyboard_protocol: bool,
        },
        WriteChars {
            chars: String,
        },
        WriteToPaneId {
            bytes: Vec < u8 >,
            pane_id: PaneId,
        },
        WriteCharsToPaneId {
            chars: String,
            pane_id: PaneId,
        },
        Paste {
            chars: String,
            pane_id: Option < PaneId >,
        },
        SwitchToMode {
            input_mode: InputMode,
        },
        SwitchModeForAllClients {
            input_mode: InputMode,
        },
        Resize {
            resize: Resize,
            direction: Option < Direction >,
        },
        FocusNextPane,
        FocusPreviousPane,
        FocusLastPane,
        SwitchFocus,
        MoveFocus {
            direction: Direction,
        },
        MoveFocusOrTab {
            direction: Direction,
        },
        MovePane {
            direction: Option < Direction >,
        },
        MovePaneBackwards,
        ClearScreen,
        DumpScreen {
            file_path: Option < String >,
            include_scrollback: bool,
            pane_id: Option < PaneId >,
            ansi: bool,
        },
        DumpLayout,
        SaveSession,
        EditScrollback {
            ansi: bool,
        },
        ScrollUp,
        ScrollUpAt {
            position: Position,
        },
        ScrollDown,
        ScrollDownAt {
            position: Position,
        },
        ScrollToPreviousPrompt,
        ScrollToNextPrompt,
        SelectCommandAtScrollPosition,
        CopyLastCommandOutput,
        ScrollToBottom,
        ScrollToTop,
        PageScrollUp,
        PageScrollDown,
        HalfPageScrollUp,
        HalfPageScrollDown,
        ToggleFocusFullscreen,
        ToggleFocusNoUiFullscreen,
        TogglePaneFrames,
        SetPaneFrameStyle(PaneFrameStyle, ),
        ToggleActiveSyncTab,
        NewPane {
            direction: Option < Direction >,
            pane_name: Option < String >,
            start_suppressed: bool,
        },
        NewBlockingPane {
            placement: NewPanePlacement,
            pane_name: Option < String >,
            command: Option < RunCommandAction >,
            unblock_condition: Option < UnblockCondition >,
            near_current_pane: bool,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        EditFile {
            payload: OpenFilePayload,
            direction: Option < Direction >,
            floating: bool,
            in_place: bool,
            close_replaced_pane: bool,
            start_suppressed: bool,
            coordinates: Option < FloatingPaneCoordinates >,
            near_current_pane: bool,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        NewFloatingPane {
            command: Option < RunCommandAction >,
            pane_name: Option < String >,
            coordinates: Option < FloatingPaneCoordinates >,
            near_current_pane: bool,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        NewTiledPane {
            direction: Option < Direction >,
            command: Option < RunCommandAction >,
            pane_name: Option < String >,
            near_current_pane: bool,
            no_focus: bool,
            borderless: Option < bool >,
            tab_id: Option < usize >,
        },
        NewInPlacePane {
            command: Option < RunCommandAction >,
            pane_name: Option < String >,
            near_current_pane: bool,
            no_focus: bool,
            pane_id_to_replace: Option < PaneId >,
            close_replaced_pane: bool,
            tab_id: Option < usize >,
        },
        NewStackedPane {
            command: Option < RunCommandAction >,
            pane_name: Option < String >,
            near_current_pane: bool,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        TogglePaneEmbedOrFloating,
        ToggleFloatingPanes,
        ShowFloatingPanes {
            tab_id: Option < usize >,
        },
        HideFloatingPanes {
            tab_id: Option < usize >,
        },
        AreFloatingPanesVisible {
            tab_id: Option < usize >,
        },
        CloseFocus,
        PaneNameInput {
            input: Vec < u8 >,
        },
        UndoRenamePane,
        NewTab {
            tiled_layout: Option < TiledPaneLayout >,
            floating_layouts: Vec < FloatingPaneLayout >,
            swap_tiled_layouts: Option < Vec < SwapTiledLayout > >,
            swap_floating_layouts: Option < Vec < SwapFloatingLayout > >,
            tab_name: Option < String >,
            should_change_focus_to_new_tab: bool,
            cwd: Option < PathBuf >,
            initial_panes: Option < Vec < CommandOrPlugin > >,
            first_pane_unblock_condition: Option < UnblockCondition >,
        },
        NoOp,
        GoToNextTab,
        GoToPreviousTab,
        CloseTab,
        GoToTab {
            index: u32,
        },
        GoToTabName {
            name: String,
            create: bool,
        },
        ToggleTab,
        TabNameInput {
            input: Vec < u8 >,
        },
        UndoRenameTab,
        MoveTab {
            direction: Direction,
        },
        Run {
            command: RunCommandAction,
            near_current_pane: bool,
            no_focus: bool,
        },
        SetPaneColor {
            pane_id: PaneId,
            fg: Option < String >,
            bg: Option < String >,
        },
        Detach,
        SetDarkTheme,
        SetLightTheme,
        ToggleTheme,
        SwitchSession {
            name: String,
            tab_position: Option < usize >,
            pane_id: Option < (u32 , bool) >,
            layout: Option < LayoutInfo >,
            cwd: Option < PathBuf >,
        },
        LaunchOrFocusPlugin {
            plugin: RunPluginOrAlias,
            should_float: bool,
            move_to_focused_tab: bool,
            should_open_in_place: bool,
            close_replaced_pane: bool,
            skip_cache: bool,
            tab_id: Option < usize >,
        },
        LaunchPlugin {
            plugin: RunPluginOrAlias,
            should_float: bool,
            should_open_in_place: bool,
            close_replaced_pane: bool,
            skip_cache: bool,
            cwd: Option < PathBuf >,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        MouseEvent {
            event: MouseEvent,
        },
        Copy,
        Confirm,
        Deny,
        SkipConfirm {
            action: Box < Action >,
        },
        SearchInput {
            input: Vec < u8 >,
        },
        Search {
            direction: SearchDirection,
        },
        SearchToggleOption {
            option: SearchOption,
        },
        ToggleMouseMode,
        PreviousSwapLayout,
        NextSwapLayout,
        OverrideLayout {
            tabs: Vec < TabLayoutInfo >,
            retain_existing_terminal_panes: bool,
            retain_existing_plugin_panes: bool,
            apply_only_to_active_tab: bool,
        },
        QueryTabNames,
        NewTiledPluginPane {
            plugin: RunPluginOrAlias,
            pane_name: Option < String >,
            skip_cache: bool,
            cwd: Option < PathBuf >,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        NewFloatingPluginPane {
            plugin: RunPluginOrAlias,
            pane_name: Option < String >,
            skip_cache: bool,
            cwd: Option < PathBuf >,
            coordinates: Option < FloatingPaneCoordinates >,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        NewInPlacePluginPane {
            plugin: RunPluginOrAlias,
            pane_name: Option < String >,
            skip_cache: bool,
            close_replaced_pane: bool,
            no_focus: bool,
            tab_id: Option < usize >,
        },
        StartOrReloadPlugin {
            plugin: RunPluginOrAlias,
        },
        CloseTerminalPane {
            pane_id: u32,
        },
        ClosePluginPane {
            pane_id: u32,
        },
        FocusTerminalPaneWithId {
            pane_id: u32,
            should_float_if_hidden: bool,
            should_be_in_place_if_hidden: bool,
        },
        FocusPluginPaneWithId {
            pane_id: u32,
            should_float_if_hidden: bool,
            should_be_in_place_if_hidden: bool,
        },
        RenameTerminalPane {
            pane_id: u32,
            name: Vec < u8 >,
        },
        RenamePluginPane {
            pane_id: u32,
            name: Vec < u8 >,
        },
        RenameTab {
            tab_index: u32,
            name: Vec < u8 >,
        },
        GoToTabById {
            id: u64,
        },
        CloseTabById {
            id: u64,
        },
        RenameTabById {
            id: u64,
            name: String,
        },
        BreakPane,
        BreakPaneRight,
        BreakPaneLeft,
        FocusHostSession,
        FocusGuestSession,
        ToggleHostFullscreen,
        RenameSession {
            name: String,
        },
        CliPipe {
            pipe_id: String,
            name: Option < String >,
            payload: Option < String >,
            args: Option < BTreeMap < String , String > >,
            plugin: Option < String >,
            configuration: Option < BTreeMap < String , String > >,
            launch_new: bool,
            skip_cache: bool,
            floating: Option < bool >,
            in_place: Option < bool >,
            cwd: Option < PathBuf >,
            pane_title: Option < String >,
        },
        KeybindPipe {
            name: Option < String >,
            payload: Option < String >,
            args: Option < BTreeMap < String , String > >,
            plugin: Option < String >,
            plugin_id: Option < u32 >,
            configuration: Option < BTreeMap < String , String > >,
            launch_new: bool,
            skip_cache: bool,
            floating: Option < bool >,
            in_place: Option < bool >,
            cwd: Option < PathBuf >,
            pane_title: Option < String >,
        },
        ListClients,
        ListPanes {
            show_tab: bool,
            show_command: bool,
            show_state: bool,
            show_geometry: bool,
            show_all: bool,
            output_json: bool,
        },
        ListTabs {
            show_state: bool,
            show_dimensions: bool,
            show_panes: bool,
            show_layout: bool,
            show_all: bool,
            output_json: bool,
        },
        CurrentTabInfo {
            output_json: bool,
        },
        TogglePanePinned,
        StackPanes {
            pane_ids: Vec < PaneId >,
        },
        ChangeFloatingPaneCoordinates {
            pane_id: PaneId,
            coordinates: FloatingPaneCoordinates,
        },
        TogglePaneBorderless {
            pane_id: PaneId,
        },
        SetPaneBorderless {
            pane_id: PaneId,
            borderless: bool,
        },
        TogglePaneInGroup,
        ToggleGroupMarking,
        ScrollUpByPaneId {
            pane_id: PaneId,
        },
        ScrollDownByPaneId {
            pane_id: PaneId,
        },
        ScrollToTopByPaneId {
            pane_id: PaneId,
        },
        ScrollToBottomByPaneId {
            pane_id: PaneId,
        },
        PageScrollUpByPaneId {
            pane_id: PaneId,
        },
        PageScrollDownByPaneId {
            pane_id: PaneId,
        },
        HalfPageScrollUpByPaneId {
            pane_id: PaneId,
        },
        HalfPageScrollDownByPaneId {
            pane_id: PaneId,
        },
        ResizeByPaneId {
            pane_id: PaneId,
            resize: Resize,
            direction: Option < Direction >,
        },
        MovePaneByPaneId {
            pane_id: PaneId,
            direction: Option < Direction >,
        },
        MovePaneBackwardsByPaneId {
            pane_id: PaneId,
        },
        ClearScreenByPaneId {
            pane_id: PaneId,
        },
        EditScrollbackByPaneId {
            pane_id: PaneId,
            ansi: bool,
        },
        ToggleFocusFullscreenByPaneId {
            pane_id: PaneId,
        },
        ToggleFocusNoUiFullscreenByPaneId {
            pane_id: PaneId,
        },
        TogglePaneEmbedOrFloatingByPaneId {
            pane_id: PaneId,
        },
        CloseFocusByPaneId {
            pane_id: PaneId,
        },
        RenamePaneByPaneId {
            pane_id: Option < PaneId >,
            name: Vec < u8 >,
        },
        UndoRenamePaneByPaneId {
            pane_id: PaneId,
        },
        TogglePanePinnedByPaneId {
            pane_id: PaneId,
        },
        FocusPaneByPaneId {
            pane_id: PaneId,
        },
        UndoRenameTabByTabId {
            id: u64,
        },
        ToggleActiveSyncTabByTabId {
            id: u64,
        },
        ToggleFloatingPanesByTabId {
            id: u64,
        },
        PreviousSwapLayoutByTabId {
            id: u64,
        },
        NextSwapLayoutByTabId {
            id: u64,
        },
        MoveTabByTabId {
            id: u64,
            direction: Direction,
        },
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum BareKey {
        PageDown,
        PageUp,
        Left,
        Down,
        Up,
        Right,
        Home,
        End,
        Backspace,
        Delete,
        Insert,
        F(u8, ),
        Char(char, ),
        Tab,
        Esc,
        Enter,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        Menu,
    }

    pub type ClientId = u16;

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct Column(pub usize, );

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum CommandOrPlugin {
        Command(RunCommandAction, ),
        Plugin(RunPluginOrAlias, ),
        File(FileToOpen, ),
    }

    pub type Context = BTreeMap < String , String >;

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum Direction {
        Left,
        Right,
        Up,
        Down,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct FileToOpen {
        pub path: PathBuf,
        pub line_number: Option < usize >,
        pub cwd: Option < PathBuf >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct FloatingPaneCoordinates {
        pub x: Option < PercentOrFixed >,
        pub y: Option < PercentOrFixed >,
        pub width: Option < PercentOrFixed >,
        pub height: Option < PercentOrFixed >,
        pub pinned: Option < bool >,
        pub borderless: Option < bool >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct FloatingPaneLayout {
        pub name: Option < String >,
        pub height: Option < PercentOrFixed >,
        pub width: Option < PercentOrFixed >,
        pub x: Option < PercentOrFixed >,
        pub y: Option < PercentOrFixed >,
        pub pinned: Option < bool >,
        pub borderless: Option < bool >,
        pub run: Option < Run >,
        pub focus: Option < bool >,
        pub already_running: bool,
        pub pane_initial_contents: Option < String >,
        pub logical_position: Option < usize >,
        pub default_fg: Option < String >,
        pub default_bg: Option < String >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum InputMode {
        # [serde (alias = "normal")]
        Normal,
        # [serde (alias = "locked")]
        Locked,
        # [serde (alias = "resize")]
        Resize,
        # [serde (alias = "pane")]
        Pane,
        # [serde (alias = "tab")]
        Tab,
        # [serde (alias = "scroll")]
        Scroll,
        # [serde (alias = "entersearch")]
        EnterSearch,
        # [serde (alias = "search")]
        Search,
        # [serde (alias = "renametab")]
        RenameTab,
        # [serde (alias = "renamepane")]
        RenamePane,
        # [serde (alias = "session")]
        Session,
        # [serde (alias = "move")]
        Move,
        # [serde (alias = "prompt")]
        Prompt,
        # [serde (alias = "tmux")]
        Tmux,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum KeyModifier {
        Ctrl,
        Alt,
        Shift,
        Super,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub struct KeyWithModifier {
        pub bare_key: BareKey,
        pub key_modifiers: BTreeSet < KeyModifier >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum LayoutConstraint {
        MaxPanes(usize, ),
        MinPanes(usize, ),
        ExactPanes(usize, ),
        NoConstraint,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum LayoutInfo {
        BuiltIn(String, ),
        File(String, LayoutMetadata, ),
        Url(String, ),
        Stringified(String, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct LayoutMetadata {
        pub tabs: Vec < TabMetadata >,
        pub creation_time: String,
        pub update_time: String,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct Line(pub isize, );

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct MouseEvent {
        pub event_type: MouseEventType,
        pub left: bool,
        pub right: bool,
        pub middle: bool,
        pub wheel_up: bool,
        pub wheel_down: bool,
        # [serde (default)]
        pub wheel_left: bool,
        # [serde (default)]
        pub wheel_right: bool,
        pub shift: bool,
        pub alt: bool,
        pub ctrl: bool,
        pub position: Position,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum MouseEventType {
        Press,
        Release,
        Motion,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum NewPanePlacement {
        NoPreference {
            borderless: Option < bool >,
        },
        Tiled {
            direction: Option < Direction >,
            borderless: Option < bool >,
        },
        Floating(Option < FloatingPaneCoordinates >, ),
        InPlace {
            pane_id_to_replace: Option < PaneId >,
            close_replaced_pane: bool,
            borderless: Option < bool >,
        },
        Stacked {
            pane_id_to_stack_under: Option < PaneId >,
            borderless: Option < bool >,
        },
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct OpenFilePayload {
        pub path: PathBuf,
        pub line_number: Option < usize >,
        pub cwd: Option < PathBuf >,
        pub originating_plugin: Option < OriginatingPlugin >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct OriginatingPlugin {
        pub plugin_id: u32,
        pub client_id: ClientId,
        pub context: Context,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    # [serde (rename_all = "lowercase")]
    pub enum PaneFrameStyle {
        Full,
        Titles,
        None,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub enum PaneId {
        Terminal(u32, ),
        Plugin(u32, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct PaneMetadata {
        pub name: Option < String >,
        pub is_plugin: bool,
        pub is_builtin_plugin: bool,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum PercentOrFixed {
        Percent(usize, ),
        Fixed(usize, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct PluginAlias {
        pub name: String,
        pub configuration: Option < PluginUserConfiguration >,
        pub initial_cwd: Option < PathBuf >,
        pub run_plugin: Option < RunPlugin >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
    pub struct PluginTag(pub String, );

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct PluginUserConfiguration(pub BTreeMap < String , String >, );

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct Position {
        pub line: Line,
        pub column: Column,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum Resize {
        Increase,
        Decrease,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum Run {
        # [serde (rename = "plugin")]
        Plugin(RunPluginOrAlias, ),
        # [serde (rename = "command")]
        Command(RunCommand, ),
        EditFile(PathBuf, Option < usize >, Option < PathBuf >, ),
        Cwd(PathBuf, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct RunCommand {
        # [serde (alias = "cmd")]
        pub command: PathBuf,
        # [serde (default)]
        pub args: Vec < String >,
        # [serde (default)]
        pub cwd: Option < PathBuf >,
        # [serde (default)]
        pub hold_on_close: bool,
        # [serde (default)]
        pub hold_on_start: bool,
        # [serde (default)]
        pub originating_plugin: Option < OriginatingPlugin >,
        # [serde (default)]
        pub use_terminal_title: bool,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct RunCommandAction {
        # [serde (rename = "cmd")]
        pub command: PathBuf,
        # [serde (default)]
        pub args: Vec < String >,
        # [serde (default)]
        pub cwd: Option < PathBuf >,
        # [serde (default)]
        pub direction: Option < Direction >,
        # [serde (default)]
        pub hold_on_close: bool,
        # [serde (default)]
        pub hold_on_start: bool,
        # [serde (default)]
        pub originating_plugin: Option < OriginatingPlugin >,
        # [serde (default)]
        pub use_terminal_title: bool,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct RunPlugin {
        # [serde (default)]
        pub _allow_exec_host_cmd: bool,
        pub location: RunPluginLocation,
        pub configuration: PluginUserConfiguration,
        pub initial_cwd: Option < PathBuf >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum RunPluginLocation {
        File(PathBuf, ),
        Zellij(PluginTag, ),
        Remote(String, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum RunPluginOrAlias {
        RunPlugin(RunPlugin, ),
        Alias(PluginAlias, ),
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum SearchDirection {
        Down,
        Up,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum SearchOption {
        CaseSensitivity,
        WholeWord,
        Wrap,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum SplitDirection {
        Horizontal,
        Vertical,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum SplitSize {
        # [serde (alias = "percent")]
        Percent(usize, ),
        # [serde (alias = "fixed")]
        Fixed(usize, ),
    }

    pub type SwapFloatingLayout = (BTreeMap < LayoutConstraint , Vec < FloatingPaneLayout > > , Option < String > ,);

    pub type SwapTiledLayout = (BTreeMap < LayoutConstraint , TiledPaneLayout > , Option < String >);

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct TabLayoutInfo {
        pub tab_index: usize,
        pub tab_name: Option < String >,
        pub tiled_layout: TiledPaneLayout,
        pub floating_layouts: Vec < FloatingPaneLayout >,
        pub swap_tiled_layouts: Option < Vec < SwapTiledLayout > >,
        pub swap_floating_layouts: Option < Vec < SwapFloatingLayout > >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct TabMetadata {
        pub panes: Vec < PaneMetadata >,
        pub name: Option < String >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub struct TiledPaneLayout {
        pub children_split_direction: SplitDirection,
        pub name: Option < String >,
        pub children: Vec < TiledPaneLayout >,
        pub split_size: Option < SplitSize >,
        pub run: Option < Run >,
        pub borderless: Option < bool >,
        pub focus: Option < bool >,
        pub external_children_index: Option < usize >,
        pub children_are_stacked: bool,
        pub is_expanded_in_stack: bool,
        pub exclude_from_sync: Option < bool >,
        pub run_instructions_to_ignore: Vec < Option < Run > >,
        pub hide_floating_panes: bool,
        pub pane_initial_contents: Option < String >,
        pub default_fg: Option < String >,
        pub default_bg: Option < String >,
    }

    #[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
    pub enum UnblockCondition {
        OnExitSuccess,
        OnExitFailure,
        OnAnyExit,
    }

}

pub use action_mirror::Action as ZellijActionMirror;

impl TryFrom<&zellij_utils::input::actions::Action> for ZellijActionMirror {
    type Error = serde_json::Error;

    fn try_from(action: &zellij_utils::input::actions::Action) -> Result<Self, Self::Error> {
        serde_json::from_value(serde_json::to_value(action)?)
    }
}

impl ZellijActionMirror {
    pub fn try_into_zellij(&self) -> Result<zellij_utils::input::actions::Action, serde_json::Error> {
        serde_json::from_value(serde_json::to_value(self)?)
    }
}
